### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by qingleer** [chengzijian/ai-hongbao#3]
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "wx/hongbao.py", line 13, in <module>
    bot = Bot(cache_path=True)
  File "/usr/local/lib/python2.7/dist-packages/wxpy/api/bot.py", line 88, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by ontheway1215** [comment]
将
`bot = Bot(cache_path=True)`改为
`
bot = Bot(cache_path=True, console_qr=True)
`

**Comment by lovezm** [comment]
我运行报错 是要安装什么包吗？

**Comment by lovezm** [comment]
@ontheway1215 在控制台打印二维码  扫不出来啊。。。

**Comment by lovezm** [comment]
c:\ai-hongbao>python wx/hongbao.py
Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Loading the contact, this may take a little while.
Traceback (most recent call last):
  File "wx/hongbao.py", line 13, in <module>
    bot = Bot(cache_path=True)
  File "C:\Python27\lib\site-packages\wxpy\api\bot.py", line 88, in __init__
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined

**Comment by krzover** [comment]
这是你的微信限制了web端登录,可以登录window版或者移动版...扫码登录官网的网页版看看提示就明白
