### ISSUE TITLE
扫描二维码登陆后报错

### ISSUE THREAD

**Issue by ultraxia** [chengzijian/ai-hongbao#5]
报错内容
Traceback (most recent call last):
  File "hongbao.py", line 13, in <module>
    bot = Bot(cache_path=True,console_qr=True)
  File "/usr/lib/python2.7/site-packages/wxpy/api/bot.py", line 86, in __init__
    loginCallback=login_callback, exitCallback=logout_callback
  File "/usr/lib/python2.7/site-packages/itchat/components/register.py", line 30, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 66, in login
    self.show_mobile_login()
  File "/usr/lib/python2.7/site-packages/itchat/components/login.py", line 212, in show_mobile_login
    self.loginInfo['url'], self.loginInfo['pass_ticket'])
KeyError: 'pass_ticket'

**Comment by webbrain-one** [comment]
Hi~ 已经提交 PR #6 了，主要修复扫描二维码登录后报错 `KeyError: 'pass_ticket'` 的问题，麻烦看一下～
